version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    user: postgres
  web:
    build: 
      context: .
      dockerfile: docker/Dockerfile.app
    command: ./docker/run-app.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db